/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author hsund
 */
public class AndraMinaUppgifter extends javax.swing.JFrame {
    private InfDB idb;
    private String uppgifterna;

    /**
     * Creates new form AndraMinaUppgifter
     */
    public AndraMinaUppgifter(InfDB idb) {
        this.idb = idb;
        this.uppgifterna = uppgifterna;
        initComponents();
        hamtaFornamn();
        hamtaEfternamn();
        hamtaAdress();
        hamtaEpost();
        hamtaTelefon();
        hamtaAnstDatum();
        hamtaLosen();
        hamtaAvdelning();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAnstDatum = new javax.swing.JLabel();
        lblLosen = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        btnSpara = new javax.swing.JButton();
        tfFornamn = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfAnstDatum = new javax.swing.JTextField();
        tfLosen = new javax.swing.JTextField();
        tfAvdelning = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFornamn.setText("Förnamn:");

        lblEfternamn.setText("Efternamn:");

        lblAdress.setText("Adress:");

        lblEpost.setText("Epost:");

        lblTelefon.setText("Telefon:");

        lblAnstDatum.setText("Anställningsdatum:");

        lblLosen.setText("Lösenord:");

        lblAvdelning.setText("Avdelning:");

        btnSpara.setText("Spara ändringar");

        tfFornamn.setText("jTextField1");

        tfEfternamn.setText("jTextField2");

        tfAdress.setText("jTextField3");

        tfEpost.setText("jTextField4");

        tfTelefon.setText("jTextField5");

        tfAnstDatum.setText("jTextField6");

        tfLosen.setText("jTextField7");

        tfAvdelning.setText("jTextField8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFornamn)
                        .addGap(18, 18, 18)
                        .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEfternamn)
                            .addComponent(lblAdress)
                            .addComponent(lblEpost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnstDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfAnstDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvdelning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLosen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSpara)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(lblTelefon)
                    .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternamn)
                    .addComponent(lblAnstDatum)
                    .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnstDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(lblLosen)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(lblAvdelning)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnSpara)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void hamtaFornamn()
    {
        String sqlFraga = "SELECT fornamn FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String fornamn = idb.fetchSingle(sqlFraga);
            tfFornamn.setText(fornamn);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaEfternamn()
    {
        String sqlFraga = "SELECT efternamn FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String efternamn = idb.fetchSingle(sqlFraga);
            tfEfternamn.setText(efternamn);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAdress()
    {
        String sqlFraga = "SELECT adress FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String adress = idb.fetchSingle(sqlFraga);
            tfAdress.setText(adress);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaEpost()
    {
        String sqlFraga = "SELECT epost FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String epost = idb.fetchSingle(sqlFraga);
            tfEpost.setText(epost);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaTelefon()
    {
        String sqlFraga = "SELECT telefon FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String telefon = idb.fetchSingle(sqlFraga);
            tfTelefon.setText(telefon);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAnstDatum()
    {
        String sqlFraga = "SELECT anstallningsdatum FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String anstDatum = idb.fetchSingle(sqlFraga);
            tfAnstDatum.setText(anstDatum);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaLosen()
    {
        String sqlFraga = "SELECT losenord FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String losenord = idb.fetchSingle(sqlFraga);
            tfLosen.setText(losenord);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAvdelning()
    {
        String sqlFraga = "SELECT avdelning FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String avdelning = idb.fetchSingle(sqlFraga);
            tfAvdelning.setText(avdelning);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //AndraMinaUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAnstDatum;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLosen;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAnstDatum;
    private javax.swing.JTextField tfAvdelning;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfLosen;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
