/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/**
 *
 * @author hsund
 */
public class AndraMinaUppgifter extends javax.swing.JFrame {
    private InfDB idb;
    private String uppgifterna;

    /**
     * Creates new form AndraMinaUppgifter
     */
    public AndraMinaUppgifter(InfDB idb,String uppgifterna) {
        this.idb = idb;
        this.uppgifterna = uppgifterna;
        initComponents();
        hamtaFornamn();
        hamtaEfternamn();
        hamtaAdress();
        hamtaEpost();
        hamtaTelefon();
        hamtaAnstDatum();
        hamtaLosen();
        hamtaAvdelning();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAnstDatum = new javax.swing.JLabel();
        lblLosen = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        btnSpara = new javax.swing.JButton();
        tfFornamn = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfAnstDatum = new javax.swing.JTextField();
        tfLosen = new javax.swing.JTextField();
        tfAvdelning = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFornamn.setText("Förnamn:");

        lblEfternamn.setText("Efternamn:");

        lblAdress.setText("Adress:");

        lblEpost.setText("Epost:");

        lblTelefon.setText("Telefon:");

        lblAnstDatum.setText("Anställningsdatum:");

        lblLosen.setText("Lösenord:");

        lblAvdelning.setText("Avdelning:");

        btnSpara.setText("Spara ändringar");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        tfFornamn.setText("jTextField1");

        tfEfternamn.setText("jTextField2");

        tfAdress.setText("jTextField3");

        tfEpost.setText("jTextField4");

        tfTelefon.setText("jTextField5");

        tfAnstDatum.setText("jTextField6");

        tfLosen.setText("jTextField7");

        tfAvdelning.setText("jTextField8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvdelning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSpara)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFornamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnstDatum)
                            .addComponent(lblLosen))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(tfAnstDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(tfLosen))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfAvdelning))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefon)
                        .addGap(81, 81, 81)
                        .addComponent(tfTelefon))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEpost)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEfternamn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAdress)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfAdress)
                            .addComponent(tfEfternamn)
                            .addComponent(tfEpost))))
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEfternamn))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnstDatum)
                    .addComponent(tfAnstDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosen)
                    .addComponent(tfLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(tfAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpara))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:
        String fornamn = tfFornamn.getText();
        String efternamn = tfEfternamn.getText();
        String adress = tfAdress.getText();
        String epost = tfEpost.getText();
        String telefon = tfTelefon.getText();
        String anstDatum = tfAnstDatum.getText();
        String losen = tfLosen.getText();
        String avdelning = tfAvdelning.getText();
        
        if(!Validering.isOnlyLetters(fornamn)&& !Validering.isOnlyLetters(efternamn)&&
                !Validering.isValidDatum(anstDatum) && !Validering.isValidLosenord(losen)&&
                !Validering.isValidEpost(epost))
        {
            return;
        }
        
    try
    {
        String sql = "UPDATE anstalld SET fornamn = '" + fornamn + "', efternamn = '" + 
                efternamn + "',adress = '" + adress + "', epost = '" + epost + "', telefon = '"
                + telefon + "', anstallningsdatum = '" + anstDatum + "', losenord = '" + losen
                + "', avdelning = '" + avdelning + "' WHERE aid = " + uppgifterna;
        idb.update(sql);
        JOptionPane.showMessageDialog(null, "Uppgifterna har uppdaterats!");
    }
    catch (InfException ex)
    {
        JOptionPane.showMessageDialog(null, "Något gick fel: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnSparaActionPerformed

    
    public void hamtaFornamn()
    {
        String sqlFraga = "SELECT fornamn FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String fornamn = idb.fetchSingle(sqlFraga);
            tfFornamn.setText(fornamn);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaEfternamn()
    {
        String sqlFraga = "SELECT efternamn FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String efternamn = idb.fetchSingle(sqlFraga);
            tfEfternamn.setText(efternamn);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAdress()
    {
        String sqlFraga = "SELECT adress FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String adress = idb.fetchSingle(sqlFraga);
            tfAdress.setText(adress);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaEpost()
    {
        String sqlFraga = "SELECT epost FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String epost = idb.fetchSingle(sqlFraga);
            tfEpost.setText(epost);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaTelefon()
    {
        String sqlFraga = "SELECT telefon FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String telefon = idb.fetchSingle(sqlFraga);
            tfTelefon.setText(telefon);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAnstDatum()
    {
        String sqlFraga = "SELECT anstallningsdatum FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String anstDatum = idb.fetchSingle(sqlFraga);
            tfAnstDatum.setText(anstDatum);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaLosen()
    {
        String sqlFraga = "SELECT losenord FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String losenord = idb.fetchSingle(sqlFraga);
            tfLosen.setText(losenord);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAvdelning()
    {
        String sqlFraga = "SELECT avdelning FROM anstalld WHERE aid = "+uppgifterna;
        try
        {
            String avdelning = idb.fetchSingle(sqlFraga);
            tfAvdelning.setText(avdelning);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //AndraMinaUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAnstDatum;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLosen;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAnstDatum;
    private javax.swing.JTextField tfAvdelning;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfLosen;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
