/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author elisl
 */
public class HanteraPartnersOchSamarbeten extends javax.swing.JFrame {
InfDB idb;
String aktuelltPID;
    /**
     * Creates new form HanteraPartnersOchSamarbeten
     */
    public HanteraPartnersOchSamarbeten(InfDB idb, String aktuelltPID) {
        this.idb = idb;
        this.aktuelltPID = aktuelltPID;
        initComponents();
        listaDelaktigaPartners();
        listaDelaktigaHandlaggare();
        listaTillgangligaPartners();
        listaTillgangligaHandlaggare();
    }
    public void listaDelaktigaHandlaggare(){
try{
     ArrayList<String> anstallda =  idb.fetchColumn("SELECT concat('AID: ',aid,'  ', fornamn,' ',efternamn) FROM anstalld where aid in(Select aid from ans_proj where pid = "+aktuelltPID+") and aid in(select aid from handlaggare)");
     DefaultListModel<String> overforingsLista = new DefaultListModel<>();
            for(String a : anstallda){
                overforingsLista.addElement(a); }
            listaDelaktigaHandlaggare.setModel(overforingsLista);
}catch(InfException ex){
    System.out.println(ex.getMessage());
}
    }
       public void listaTillgangligaHandlaggare(){
try{
     ArrayList<String> anstallda =  idb.fetchColumn("SELECT concat('AID: ',aid,'  ', fornamn,' ',efternamn) FROM anstalld where aid not in(Select aid from ans_proj where pid = "+aktuelltPID+") and aid in(select aid from handlaggare)");
     DefaultListModel<String> overforingsLista = new DefaultListModel<>();
            for(String a : anstallda){
                overforingsLista.addElement(a); }
            listaTillgangligaHandlaggare.setModel(overforingsLista);
}catch(InfException ex){
    System.out.println(ex.getMessage());
}
    }
               public void listaTillgangligaPartners(){
try{
     ArrayList<String> partners =  idb.fetchColumn("SELECT concat('PID: ',pid,'  ', namn) FROM partner where pid not in(Select partner_pid from projekt_partner where pid ="+aktuelltPID+")");
     DefaultListModel<String> overforingsLista = new DefaultListModel<>();
            for(String a : partners){
                overforingsLista.addElement(a); }
            listaTillgangligaPartners.setModel(overforingsLista);
}catch(InfException ex){
    System.out.println(ex.getMessage());
}
    }
        public void listaDelaktigaPartners(){
try{
     ArrayList<String> partners =  idb.fetchColumn("SELECT concat('PID: ',pid,'  ', namn) FROM partner where pid in(Select partner_pid from projekt_partner where pid ="+aktuelltPID+")");
     DefaultListModel<String> overforingsLista = new DefaultListModel<>();
            for(String a : partners){
                overforingsLista.addElement(a); }
            listaDelaktigaPartners.setModel(overforingsLista);
}catch(InfException ex){
    System.out.println(ex.getMessage());
}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDelaktigaHandlaggare = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaTillgangligaHandlaggare = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDelaktigaPartners = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaTillgangligaPartners = new javax.swing.JList<>();
        lblHandlaggareIProjektet = new javax.swing.JLabel();
        lblTillgangligaHandlaggare = new javax.swing.JLabel();
        lblPartnersIProjektet = new javax.swing.JLabel();
        lblTillgangligaPartners = new javax.swing.JLabel();
        tfSokRutaHandlaggare = new javax.swing.JTextField();
        tfSokrutaPartners = new javax.swing.JTextField();

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaDelaktigaHandlaggare.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaDelaktigaHandlaggare);

        listaTillgangligaHandlaggare.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaTillgangligaHandlaggare);

        listaDelaktigaPartners.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaDelaktigaPartners);

        listaTillgangligaPartners.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listaTillgangligaPartners);

        lblHandlaggareIProjektet.setText("Handläggare i projektet");

        lblTillgangligaHandlaggare.setText("Tillgängliga handläggare");

        lblPartnersIProjektet.setText("Partners I projektet");

        lblTillgangligaPartners.setText("Tillgängliga partners");

        tfSokRutaHandlaggare.setText("jTextField1");

        tfSokrutaPartners.setText("eeeee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHandlaggareIProjektet, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTillgangligaHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPartnersIProjektet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfSokrutaPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addComponent(lblTillgangligaPartners, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfSokRutaHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHandlaggareIProjektet)
                    .addComponent(lblTillgangligaHandlaggare)
                    .addComponent(lblPartnersIProjektet)
                    .addComponent(lblTillgangligaPartners))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSokRutaHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSokrutaPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HanteraPartnersOchSamarbeten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HanteraPartnersOchSamarbeten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HanteraPartnersOchSamarbeten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HanteraPartnersOchSamarbeten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new HanteraPartnersOchSamarbeten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblHandlaggareIProjektet;
    private javax.swing.JLabel lblPartnersIProjektet;
    private javax.swing.JLabel lblTillgangligaHandlaggare;
    private javax.swing.JLabel lblTillgangligaPartners;
    private javax.swing.JList<String> listaDelaktigaHandlaggare;
    private javax.swing.JList<String> listaDelaktigaPartners;
    private javax.swing.JList<String> listaTillgangligaHandlaggare;
    private javax.swing.JList<String> listaTillgangligaPartners;
    private javax.swing.JTextField tfSokRutaHandlaggare;
    private javax.swing.JTextField tfSokrutaPartners;
    // End of variables declaration//GEN-END:variables
}
