/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author hsund
 */
public class informationsrutaHandläggare extends javax.swing.JFrame {
    private InfDB idb;
    private String informationHandlaggare;

    /**
     * Creates new form informationsrutaHandläggare
     */
    public informationsrutaHandläggare(InfDB idb, String informationHandlaggare) {
        this.idb = idb;
        this.informationHandlaggare = informationHandlaggare;
        initComponents();
        hamtaNamn();
        hamtaEpost();
        hamtaAID();
        hamtaAdress();
        hamtaTelefon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNamnArea = new javax.swing.JLabel();
        tfEpostArea = new javax.swing.JLabel();
        tfAnstallningIdArea = new javax.swing.JLabel();
        tfAdressArea = new javax.swing.JLabel();
        tfTelefonArea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fullständigt namn:");

        jLabel2.setText("Epostadress:");

        jLabel3.setText("Anställnings-ID:");

        jLabel4.setText("Adress:");

        jLabel5.setText("Telefonnummer:");

        tfNamnArea.setText("jLabel6");

        tfEpostArea.setText("jLabel7");

        tfAnstallningIdArea.setText("jLabel8");

        tfAdressArea.setText("jLabel9");

        tfTelefonArea.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNamnArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEpostArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfAnstallningIdArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfAdressArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTelefonArea, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNamnArea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEpostArea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAnstallningIdArea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAdressArea))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTelefonArea))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hamtaNamn()
    {
        String sqlFraga = "SELECT concat (fornamn,' ',efternamn) FROM anstalld where aid="+informationHandlaggare;
        try{
        String handlaggareNamn = idb.fetchSingle(sqlFraga);
        tfNamnArea.setText(handlaggareNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    }}
        
    public void hamtaEpost()
    {
        String sqlFraga = "SELECT epost FROM anstalld WHERE aid="+informationHandlaggare;
        try
        {
            String handlaggareEpost = idb.fetchSingle(sqlFraga);
            tfEpostArea.setText(handlaggareEpost);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage()); 
        }
    }
    
    public void hamtaAID()
    {
        String sqlFraga = "SELECT aid FROM anstalld WHERE aid="+informationHandlaggare;
        try
        {
            String handlaggareId = idb.fetchSingle(sqlFraga);
            tfAnstallningIdArea.setText(handlaggareId);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAdress()
    {
        String sqlFraga = "SELECT adress FROM anstalld WHERE aid="+informationHandlaggare;
        try
        {
            String handlaggareAdress = idb.fetchSingle(sqlFraga);
            tfAdressArea.setText(handlaggareAdress);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaTelefon()
    {
        String sqlFraga = "SELECT telefon FROM anstalld WHERE aid="+informationHandlaggare;
        try
        {
            String handlaggareTelefon = idb.fetchSingle(sqlFraga);
            tfTelefonArea.setText(handlaggareTelefon);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informationsrutaHandläggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informationsrutaHandläggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informationsrutaHandläggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informationsrutaHandläggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //informationsrutaHandläggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel tfAdressArea;
    private javax.swing.JLabel tfAnstallningIdArea;
    private javax.swing.JLabel tfEpostArea;
    private javax.swing.JLabel tfNamnArea;
    private javax.swing.JLabel tfTelefonArea;
    // End of variables declaration//GEN-END:variables
}
