/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;

import oru.inf.InfDB;
import javax.swing.JOptionPane;
import oru.inf.InfException;
import java.awt.Color;

/**
 * /**
 *
 * @author jakobolofsson
 */
public class LaggTillNyPartner extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form LaggTillNyPartner
     */
    public LaggTillNyPartner(InfDB idb) {
        this.idb = idb;
        initComponents();
        lblStadFelM.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPid = new javax.swing.JLabel();
        lblPartnerNamn = new javax.swing.JLabel();
        lblKontaktperson = new javax.swing.JLabel();
        lblKontaktEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblBransch = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        tfPartnerNamn = new javax.swing.JTextField();
        tfKontaktperson = new javax.swing.JTextField();
        tfKontaktEpost = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfBransch = new javax.swing.JTextField();
        tfStad = new javax.swing.JTextField();
        btnSkapaPartner = new javax.swing.JButton();
        lblStadFelM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPid.setText("Partner-ID:");

        lblPartnerNamn.setText("Partnernamn:*");

        lblKontaktperson.setText("Kontaktperson:*");

        lblKontaktEpost.setText("Kontakt-epost:");

        lblTelefon.setText("Telefon:*");

        lblAdress.setText("Adress:*");

        lblBransch.setText("Bransch:");

        lblStad.setText("Stad:*");

        tfPartnerNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPartnerNamnActionPerformed(evt);
            }
        });

        tfStad.setForeground(new java.awt.Color(204, 204, 204));
        tfStad.setText("Skriv ID:t för staden");
        tfStad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfStadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfStadFocusLost(evt);
            }
        });

        btnSkapaPartner.setText("Skapa");
        btnSkapaPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaPartnerActionPerformed(evt);
            }
        });

        lblStadFelM.setText("Staden måste finnas i databasen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPid)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStadFelM)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPartnerNamn)
                                    .addComponent(lblKontaktperson)
                                    .addComponent(lblKontaktEpost)
                                    .addComponent(lblTelefon)
                                    .addComponent(lblAdress)
                                    .addComponent(lblBransch)
                                    .addComponent(lblStad))
                                .addGap(147, 147, 147)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPartnerNamn)
                                    .addComponent(tfKontaktperson)
                                    .addComponent(tfKontaktEpost)
                                    .addComponent(tfTelefon)
                                    .addComponent(tfAdress)
                                    .addComponent(tfBransch)
                                    .addComponent(tfStad, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSkapaPartner)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSkapaPartner)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPid)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPartnerNamn)
                            .addComponent(tfPartnerNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKontaktperson)
                            .addComponent(tfKontaktperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKontaktEpost)
                            .addComponent(tfKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefon)
                            .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdress)
                            .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBransch)
                            .addComponent(tfBransch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStad)
                            .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStadFelM)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPartnerNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPartnerNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPartnerNamnActionPerformed

    private void btnSkapaPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaPartnerActionPerformed
        boolean inDataOk = true;
        
        String partnerNamn = tfPartnerNamn.getText();
        String adress = tfAdress.getText();
        String bransch = tfBransch.getText();
        String epost = tfKontaktEpost.getText();
        String kontaktPerson = tfKontaktperson.getText();
        String stad = tfStad.getText();
        String telefon = tfTelefon.getText();
        
        try{
        // All validering    
        if(!Validering.ejTomtFalt(tfPartnerNamn)){ 
            inDataOk = false;
        }  
        if(!Validering.ejTomtFalt(tfAdress)){ 
            inDataOk = false;
        }  
        if(!Validering.ejTomtFalt(tfKontaktEpost)){ 
            inDataOk = false;
        }  
        if(!Validering.ejTomtFalt(tfKontaktperson)){ 
            inDataOk = false;
        } 
        if(!Validering.ejTomtFalt(tfTelefon)){ 
            inDataOk = false;
        }  
        if(!Validering.ejTomtFalt(tfStad)){ 
            inDataOk = false;
        }
        if(!Validering.isValidEpost(tfKontaktEpost.getText())){
            inDataOk = false;
        }
        if(!Validering.isOnlyLetters(tfKontaktperson.getText())){
            inDataOk = false;
        }
        if(idb.fetchSingle("Select sid from stad where sid=" +stad) == null){
        lblStadFelM.setForeground(Color.RED); 
        lblStadFelM.setVisible(true);
        inDataOk = false;
        }
        if (!inDataOk){
            return;
        }
        lblStadFelM.setVisible(false);
        
        // Frågan för att uppdatera information.
        String autoID = idb.getAutoIncrement("partner", "pid");
        String sql = "INSERT INTO partner (pid, namn, kontaktperson, kontaktepost, telefon, adress, branch, stad) " +
             "VALUES ('" + autoID + "', '" + partnerNamn + "', '" + kontaktPerson + "', '" + epost + "', '" + telefon + "', '" +
             adress + "', '" + bransch + "', '" + stad + "')";
        idb.insert(sql);
        JOptionPane.showMessageDialog(null, "Partnern har lagts till!");   
        }
        
        catch (InfException ex) {
    
        JOptionPane.showMessageDialog(null, "Något gick fel: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSkapaPartnerActionPerformed

    private void tfStadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfStadFocusGained
        if (tfStad.getText().equals("Skriv ID:t för staden")) {
            tfStad.setText("");
            tfStad.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfStadFocusGained

    private void tfStadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfStadFocusLost
        if (tfStad.getText().isEmpty()) {
            tfStad.setText("Skriv ID:t för staden");
            tfStad.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfStadFocusLost
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillNyPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillNyPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillNyPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillNyPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new LaggTillNyPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkapaPartner;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBransch;
    private javax.swing.JLabel lblKontaktEpost;
    private javax.swing.JLabel lblKontaktperson;
    private javax.swing.JLabel lblPartnerNamn;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblStadFelM;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfBransch;
    private javax.swing.JTextField tfKontaktEpost;
    private javax.swing.JTextField tfKontaktperson;
    private javax.swing.JTextField tfPartnerNamn;
    private javax.swing.JTextField tfStad;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
