/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author elisl
 */
public class MenyAdmin extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form
     */
    public MenyAdmin(InfDB idb,String inloggadAnvandare) {
     
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblInloggadAnvandare.setText(inloggadAnvandare);

       
                
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInloggadAnvandare = new javax.swing.JLabel();
        menyAdminHuvudPanel = new javax.swing.JTabbedPane();
        panelProjekt = new javax.swing.JPanel();
        panelLänder = new javax.swing.JPanel();
        panelPartners = new javax.swing.JPanel();
        panelAvdelningar = new javax.swing.JPanel();
        panelAnvandare = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("jLabel1");

        javax.swing.GroupLayout panelProjektLayout = new javax.swing.GroupLayout(panelProjekt);
        panelProjekt.setLayout(panelProjektLayout);
        panelProjektLayout.setHorizontalGroup(
            panelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        panelProjektLayout.setVerticalGroup(
            panelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menyAdminHuvudPanel.addTab("Projekt", panelProjekt);

        javax.swing.GroupLayout panelLänderLayout = new javax.swing.GroupLayout(panelLänder);
        panelLänder.setLayout(panelLänderLayout);
        panelLänderLayout.setHorizontalGroup(
            panelLänderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        panelLänderLayout.setVerticalGroup(
            panelLänderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menyAdminHuvudPanel.addTab("Länder", panelLänder);

        javax.swing.GroupLayout panelPartnersLayout = new javax.swing.GroupLayout(panelPartners);
        panelPartners.setLayout(panelPartnersLayout);
        panelPartnersLayout.setHorizontalGroup(
            panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        panelPartnersLayout.setVerticalGroup(
            panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menyAdminHuvudPanel.addTab("Partners", panelPartners);

        javax.swing.GroupLayout panelAvdelningarLayout = new javax.swing.GroupLayout(panelAvdelningar);
        panelAvdelningar.setLayout(panelAvdelningarLayout);
        panelAvdelningarLayout.setHorizontalGroup(
            panelAvdelningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        panelAvdelningarLayout.setVerticalGroup(
            panelAvdelningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menyAdminHuvudPanel.addTab("Avdelningar", panelAvdelningar);

        javax.swing.GroupLayout panelAnvandareLayout = new javax.swing.GroupLayout(panelAnvandare);
        panelAnvandare.setLayout(panelAnvandareLayout);
        panelAnvandareLayout.setHorizontalGroup(
            panelAnvandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        panelAnvandareLayout.setVerticalGroup(
            panelAnvandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menyAdminHuvudPanel.addTab("Användare", panelAnvandare);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menyAdminHuvudPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menyAdminHuvudPanel)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblInloggadAnvandare)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
               // new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JTabbedPane menyAdminHuvudPanel;
    private javax.swing.JPanel panelAnvandare;
    private javax.swing.JPanel panelAvdelningar;
    private javax.swing.JPanel panelLänder;
    private javax.swing.JPanel panelPartners;
    private javax.swing.JPanel panelProjekt;
    // End of variables declaration//GEN-END:variables

}