/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author elisl
 */
public class MenyAdmin extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form
     */
    public MenyAdmin(InfDB idb,String inloggadAnvandare) {
     
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblInloggadAnvandare.setText(inloggadAnvandare);

       
                
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInloggadAnvandare = new javax.swing.JLabel();
        paneHuvudPanelAdmin = new javax.swing.JTabbedPane();
        panelMinaProjekt = new javax.swing.JPanel();
        panelLander = new javax.swing.JPanel();
        panelPartners = new javax.swing.JPanel();
        panelAvdelningar = new javax.swing.JPanel();
        panelLaggTillAnvandare = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("jLabel1");

        javax.swing.GroupLayout panelMinaProjektLayout = new javax.swing.GroupLayout(panelMinaProjekt);
        panelMinaProjekt.setLayout(panelMinaProjektLayout);
        panelMinaProjektLayout.setHorizontalGroup(
            panelMinaProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelMinaProjektLayout.setVerticalGroup(
            panelMinaProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        paneHuvudPanelAdmin.addTab("Mina projekt", panelMinaProjekt);

        javax.swing.GroupLayout panelLanderLayout = new javax.swing.GroupLayout(panelLander);
        panelLander.setLayout(panelLanderLayout);
        panelLanderLayout.setHorizontalGroup(
            panelLanderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelLanderLayout.setVerticalGroup(
            panelLanderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        paneHuvudPanelAdmin.addTab("Länder", panelLander);

        javax.swing.GroupLayout panelPartnersLayout = new javax.swing.GroupLayout(panelPartners);
        panelPartners.setLayout(panelPartnersLayout);
        panelPartnersLayout.setHorizontalGroup(
            panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelPartnersLayout.setVerticalGroup(
            panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        paneHuvudPanelAdmin.addTab("Partners", panelPartners);

        javax.swing.GroupLayout panelAvdelningarLayout = new javax.swing.GroupLayout(panelAvdelningar);
        panelAvdelningar.setLayout(panelAvdelningarLayout);
        panelAvdelningarLayout.setHorizontalGroup(
            panelAvdelningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelAvdelningarLayout.setVerticalGroup(
            panelAvdelningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        paneHuvudPanelAdmin.addTab("Avdelningar", panelAvdelningar);

        javax.swing.GroupLayout panelLaggTillAnvandareLayout = new javax.swing.GroupLayout(panelLaggTillAnvandare);
        panelLaggTillAnvandare.setLayout(panelLaggTillAnvandareLayout);
        panelLaggTillAnvandareLayout.setHorizontalGroup(
            panelLaggTillAnvandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelLaggTillAnvandareLayout.setVerticalGroup(
            panelLaggTillAnvandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        paneHuvudPanelAdmin.addTab("Lägg till användare", panelLaggTillAnvandare);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneHuvudPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneHuvudPanelAdmin))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblInloggadAnvandare)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
               // new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JTabbedPane paneHuvudPanelAdmin;
    private javax.swing.JPanel panelAvdelningar;
    private javax.swing.JPanel panelLaggTillAnvandare;
    private javax.swing.JPanel panelLander;
    private javax.swing.JPanel panelMinaProjekt;
    private javax.swing.JPanel panelPartners;
    // End of variables declaration//GEN-END:variables

}