/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
/**
 *
 * @author elisl
 */
public class MenyHandlaggare extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    private String anvandarensAvdelning;

    /**
     * Creates new form MenyHandlaggare
     */
    public MenyHandlaggare(InfDB idb,String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        try{
        anvandarensAvdelning = idb.fetchSingle("SELECT avdelning FROM anstalld where epost ='"+inloggadAnvandare+"'");
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        initComponents();
        listaOverKollegor();
        listaOverProjekt();
    }
    public void listaOverKollegor(){
try{
     ArrayList<String> anstallda =  idb.fetchColumn("SELECT concat (fornamn,' ',efternamn) FROM anstalld where avdelning="+anvandarensAvdelning);
     DefaultListModel<String> overforingsLista = new DefaultListModel<>();
            for(String a : anstallda){
                overforingsLista.addElement(a); }
            listaAnstallda.setModel(overforingsLista);
}catch(InfException ex){
    System.out.println(ex.getMessage());
}
    }
    public void listaOverProjekt(){
       try{ ArrayList<String> anstallda = idb.fetchColumn("SELECT concat(projektnamn, ', ',status) from projekt where pid in(SELECT pid from ans_proj where aid in(SELECT aid from anstalld where avdelning ="+anvandarensAvdelning+"))");
       DefaultListModel<String> overforingsLista = new DefaultListModel<>();
        for(String a : anstallda){
                overforingsLista.addElement(a);
        System.out.println(a);}
        listaProjektAvdelningHandlaggare.setModel(overforingsLista);
    }catch(InfException ex){
        System.out.println(ex.getMessage());
    }}

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        huvudPanelHandlaggare = new javax.swing.JTabbedPane();
        tabMinaProjekt = new javax.swing.JPanel();
        tabMinAvdelning = new javax.swing.JPanel();
        AnstalldaScrollPane = new javax.swing.JScrollPane();
        listaAnstallda = new javax.swing.JList<>();
        lblKollegorListTitel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProjektAvdelningHandlaggare = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        tabMinaUppgifter = new javax.swing.JTabbedPane();
        tabHallbarhetsMal = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout tabMinaProjektLayout = new javax.swing.GroupLayout(tabMinaProjekt);
        tabMinaProjekt.setLayout(tabMinaProjektLayout);
        tabMinaProjektLayout.setHorizontalGroup(
            tabMinaProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        tabMinaProjektLayout.setVerticalGroup(
            tabMinaProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        huvudPanelHandlaggare.addTab("Mina Projekt", tabMinaProjekt);

        listaAnstallda.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        AnstalldaScrollPane.setViewportView(listaAnstallda);

        lblKollegorListTitel.setText("MinaKollegor");

        listaProjektAvdelningHandlaggare.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaProjektAvdelningHandlaggare);

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout tabMinAvdelningLayout = new javax.swing.GroupLayout(tabMinAvdelning);
        tabMinAvdelning.setLayout(tabMinAvdelningLayout);
        tabMinAvdelningLayout.setHorizontalGroup(
            tabMinAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMinAvdelningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabMinAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabMinAvdelningLayout.createSequentialGroup()
                        .addComponent(AnstalldaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1))
                    .addGroup(tabMinAvdelningLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblKollegorListTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        tabMinAvdelningLayout.setVerticalGroup(
            tabMinAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMinAvdelningLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblKollegorListTitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabMinAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnstalldaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        huvudPanelHandlaggare.addTab("Min Avdelning", tabMinAvdelning);
        huvudPanelHandlaggare.addTab("Mina Uppgifter", tabMinaUppgifter);
        huvudPanelHandlaggare.addTab("Hållbarhetsmål", tabHallbarhetsMal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(huvudPanelHandlaggare, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(huvudPanelHandlaggare, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new MenyHandlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AnstalldaScrollPane;
    private javax.swing.JTabbedPane huvudPanelHandlaggare;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblKollegorListTitel;
    private javax.swing.JList<String> listaAnstallda;
    private javax.swing.JList<String> listaProjektAvdelningHandlaggare;
    private javax.swing.JTabbedPane tabHallbarhetsMal;
    private javax.swing.JPanel tabMinAvdelning;
    private javax.swing.JPanel tabMinaProjekt;
    private javax.swing.JTabbedPane tabMinaUppgifter;
    // End of variables declaration//GEN-END:variables
}
