/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.awt.Color;

/**
 *
 * @author elisl
 */
public class MenyAdmin extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form
     */
    public MenyAdmin(InfDB idb, String inloggadAnvandare) {

        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblInloggadAnvandare.setText(inloggadAnvandare);
        listaOverProjekt();
        listaOverLander();
        listaOverPartners();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInloggadAnvandare = new javax.swing.JLabel();
        menyAdminHuvudPanel = new javax.swing.JTabbedPane();
        panelProjekt = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProjekt = new javax.swing.JList<>();
        tfProjektID = new javax.swing.JTextField();
        btnProjektHamtaUppgifter = new javax.swing.JButton();
        lblAllaProjekt = new javax.swing.JLabel();
        panelLänder = new javax.swing.JPanel();
        lblAllaLander = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaLander = new javax.swing.JList<>();
        btnLandHamtaUppgifter = new javax.swing.JButton();
        tfLandID = new javax.swing.JTextField();
        panelPartners = new javax.swing.JPanel();
        lblAllaPartners = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPartners = new javax.swing.JList<>();
        tfPartnerID = new javax.swing.JTextField();
        btnPartnerHamtaUppgifter = new javax.swing.JButton();
        panelAvdelningar = new javax.swing.JPanel();
        panelAnvandare = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("jLabel1");

        listaProjekt.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaProjekt);

        tfProjektID.setColumns(10);
        tfProjektID.setForeground(Color.GRAY);
        tfProjektID.setText("Ange Projekt-ID");
        tfProjektID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfProjektIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfProjektIDFocusLost(evt);
            }
        });
        tfProjektID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProjektIDActionPerformed(evt);
            }
        });

        btnProjektHamtaUppgifter.setText("Hämta uppgifter");
        btnProjektHamtaUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektHamtaUppgifterActionPerformed(evt);
            }
        });

        lblAllaProjekt.setText("Alla projekt:");

        javax.swing.GroupLayout panelProjektLayout = new javax.swing.GroupLayout(panelProjekt);
        panelProjekt.setLayout(panelProjektLayout);
        panelProjektLayout.setHorizontalGroup(
            panelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjektLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(tfProjektID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAllaProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnProjektHamtaUppgifter, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        panelProjektLayout.setVerticalGroup(
            panelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjektLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblAllaProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfProjektID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProjektHamtaUppgifter)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        menyAdminHuvudPanel.addTab("Projekt", panelProjekt);

        lblAllaLander.setText("Alla länder:");

        listaLander.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaLander);

        btnLandHamtaUppgifter.setText("Hämta uppgifter");
        btnLandHamtaUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLandHamtaUppgifterActionPerformed(evt);
            }
        });

        tfLandID.setColumns(10);
        tfLandID.setForeground(Color.GRAY);
        tfLandID.setText("Ange Land-ID");
        tfLandID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLandIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLandIDFocusLost(evt);
            }
        });
        tfLandID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLandIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLänderLayout = new javax.swing.GroupLayout(panelLänder);
        panelLänder.setLayout(panelLänderLayout);
        panelLänderLayout.setHorizontalGroup(
            panelLänderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLänderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLänderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAllaLander)
                    .addComponent(tfLandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLandHamtaUppgifter))
                .addGap(346, 346, 346))
        );
        panelLänderLayout.setVerticalGroup(
            panelLänderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLänderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAllaLander)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnLandHamtaUppgifter)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        menyAdminHuvudPanel.addTab("Länder", panelLänder);

        lblAllaPartners.setText("Alla partners:");

        listaPartners.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPartners.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaPartnersFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                listaPartnersFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(listaPartners);

        tfPartnerID.setText("Ange Partner-ID");
        tfPartnerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPartnerIDActionPerformed(evt);
            }
        });

        btnPartnerHamtaUppgifter.setText("Hämta uppgifter");
        btnPartnerHamtaUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartnerHamtaUppgifterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPartnersLayout = new javax.swing.GroupLayout(panelPartners);
        panelPartners.setLayout(panelPartnersLayout);
        panelPartnersLayout.setHorizontalGroup(
            panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPartnersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAllaPartners)
                    .addComponent(jScrollPane3)
                    .addComponent(tfPartnerID)
                    .addComponent(btnPartnerHamtaUppgifter, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        panelPartnersLayout.setVerticalGroup(
            panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPartnersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAllaPartners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tfPartnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPartnerHamtaUppgifter)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        menyAdminHuvudPanel.addTab("Partners", panelPartners);

        javax.swing.GroupLayout panelAvdelningarLayout = new javax.swing.GroupLayout(panelAvdelningar);
        panelAvdelningar.setLayout(panelAvdelningarLayout);
        panelAvdelningarLayout.setHorizontalGroup(
            panelAvdelningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        panelAvdelningarLayout.setVerticalGroup(
            panelAvdelningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        menyAdminHuvudPanel.addTab("Avdelningar", panelAvdelningar);

        javax.swing.GroupLayout panelAnvandareLayout = new javax.swing.GroupLayout(panelAnvandare);
        panelAnvandare.setLayout(panelAnvandareLayout);
        panelAnvandareLayout.setHorizontalGroup(
            panelAnvandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        panelAnvandareLayout.setVerticalGroup(
            panelAnvandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        menyAdminHuvudPanel.addTab("Användare", panelAnvandare);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menyAdminHuvudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menyAdminHuvudPanel)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblInloggadAnvandare)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void listaOverProjekt() {
        try {
            ArrayList<String> allaProjekt = idb.fetchColumn("SELECT concat(projektnamn, ', Projekt-ID: ',pid) from projekt");
            DefaultListModel<String> overforingsLista = new DefaultListModel<>();

            for (String a : allaProjekt) {
                overforingsLista.addElement(a);
                System.out.println(a);
            }
            listaProjekt.setModel(overforingsLista);

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void listaOverLander() {
        try {
            ArrayList<String> allaLander = idb.fetchColumn("SELECT concat(namn, ', Land-ID: ',lid) from land");
            DefaultListModel<String> overforingsLista = new DefaultListModel<>();

            for (String lander : allaLander) {
                overforingsLista.addElement(lander);
                System.out.println(lander);
            }
            listaLander.setModel(overforingsLista);

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    public void listaOverPartners()
    {
        try{
            ArrayList<String> allaPartners = idb.fetchColumn("SELECT concat(namn, ', Partner-ID: ',pid) from partner");
            DefaultListModel<String> overforingsLista = new DefaultListModel<>();
            
            for (String partners : allaPartners) {
                overforingsLista.addElement(partners);
                System.out.println(partners);
            }
            listaPartners.setModel(overforingsLista);
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }


    private void tfProjektIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProjektIDActionPerformed

    }//GEN-LAST:event_tfProjektIDActionPerformed

    private void btnProjektHamtaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektHamtaUppgifterActionPerformed

        String projektID = tfProjektID.getText();

        try {
            String sqlFraga = "SELECT pid FROM projekt WHERE pid = " + projektID;
            System.out.println(sqlFraga);
            String pidFinns = idb.fetchSingle(sqlFraga);
            if (projektID.equals(pidFinns)) {

                new ProjektDetaljer(idb, pidFinns).setVisible(true);
            }
        } catch (InfException ex) {
            System.out.println(ex.getMessage());

        }
    }//GEN-LAST:event_btnProjektHamtaUppgifterActionPerformed

    private void btnLandHamtaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandHamtaUppgifterActionPerformed

        String landID = tfLandID.getText();

        try {
            String sqlFraga = "SELECT lid FROM land WHERE lid = " + landID;
            System.out.println(sqlFraga);
            String lidFinns = idb.fetchSingle(sqlFraga);
            if (landID.equals(lidFinns)) {

                new LandDetaljer(idb, lidFinns).setVisible(true);
            }
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnLandHamtaUppgifterActionPerformed

    private void tfLandIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLandIDActionPerformed

    }//GEN-LAST:event_tfLandIDActionPerformed

    private void tfLandIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLandIDFocusGained

        if (tfLandID.getText().equals("Ange Land-ID")) {
            tfLandID.setText("");
            tfLandID.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfLandIDFocusGained

    private void tfLandIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLandIDFocusLost

        if (tfLandID.getText().isEmpty()) {
            tfLandID.setText("Ange Land-ID");
            tfLandID.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfLandIDFocusLost

    private void tfProjektIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProjektIDFocusGained

        if (tfProjektID.getText().equals("Ange Projekt-ID")) {
            tfProjektID.setText("");
            tfProjektID.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfProjektIDFocusGained

    private void tfProjektIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProjektIDFocusLost

        if (tfProjektID.getText().isEmpty()) {
            tfProjektID.setText("Ange Projekt-ID");
            tfProjektID.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfProjektIDFocusLost


    
    private void btnPartnerHamtaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnerHamtaUppgifterActionPerformed
        // TODO add your handling code here:
        String partnerID = tfPartnerID.getText();
        try {
            String sqlFraga = "SELECT pid FROM partner WHERE pid = " + partnerID;
            System.out.println(sqlFraga);
            String pidFinns = idb.fetchSingle(sqlFraga);
            if (partnerID.equals(pidFinns)) {

                new PartnerUppgifter(idb, pidFinns).setVisible(true);
            }
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
        
       
    }//GEN-LAST:event_btnPartnerHamtaUppgifterActionPerformed

    private void tfPartnerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPartnerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPartnerIDActionPerformed

    private void listaPartnersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaPartnersFocusGained
        // TODO add your handling code here:
        if (tfPartnerID.getText().equals("Ange Partner-ID")) {
            tfPartnerID.setText("");
            tfPartnerID.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_listaPartnersFocusGained

    private void listaPartnersFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaPartnersFocusLost
        // TODO add your handling code here:
        if (tfPartnerID.getText().isEmpty()) {
            tfPartnerID.setText("Ange Partner-ID");
            tfPartnerID.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_listaPartnersFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLandHamtaUppgifter;
    private javax.swing.JButton btnPartnerHamtaUppgifter;
    private javax.swing.JButton btnProjektHamtaUppgifter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAllaLander;
    private javax.swing.JLabel lblAllaPartners;
    private javax.swing.JLabel lblAllaProjekt;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JList<String> listaLander;
    private javax.swing.JList<String> listaPartners;
    private javax.swing.JList<String> listaProjekt;
    private javax.swing.JTabbedPane menyAdminHuvudPanel;
    private javax.swing.JPanel panelAnvandare;
    private javax.swing.JPanel panelAvdelningar;
    private javax.swing.JPanel panelLänder;
    private javax.swing.JPanel panelPartners;
    private javax.swing.JPanel panelProjekt;
    private javax.swing.JTextField tfLandID;
    private javax.swing.JTextField tfPartnerID;
    private javax.swing.JTextField tfProjektID;
    // End of variables declaration//GEN-END:variables

}
