/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/**
 *
 * @author hsund
 */
public class PartnerUppgifter extends javax.swing.JFrame {
    private InfDB idb;
    private String partnerUppgifter;

    /**
     * Creates new form PartnerUppgifter
     */
    public PartnerUppgifter(InfDB idb,String partnerUppgifter) {
        this.idb = idb;
        this.partnerUppgifter = partnerUppgifter;
        initComponents();
        hamtaPartnerId();
        hamtaNamn();
        hamtaKontaktperson();
        hamtaKontaktEpost();
        hamtaTelefon();
        hamtaAdress();
        hamtaBranch();
        hamtaStad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPartnerId = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblKontaktperson = new javax.swing.JLabel();
        lblKontaktEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        tfPartnerId = new javax.swing.JTextField();
        tfNamn = new javax.swing.JTextField();
        tfKontaktperson = new javax.swing.JTextField();
        tfKontaktEpost = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfBranch = new javax.swing.JTextField();
        tfStad = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPartnerId.setText("Partner-ID:");

        lblNamn.setText("Namn:");

        lblKontaktperson.setText("Kontaktperson:");

        lblKontaktEpost.setText("Kontakt-epost:");

        lblTelefon.setText("Telefon:");

        lblAdress.setText("Adress:");

        lblBranch.setText("Branch:");

        lblStad.setText("Stad:");

        tfPartnerId.setText("jTextField1");

        tfNamn.setText("jTextField2");

        tfKontaktperson.setText("jTextField3");

        tfKontaktEpost.setText("jTextField4");

        tfTelefon.setText("jTextField5");

        tfAdress.setText("jTextField6");

        tfBranch.setText("jTextField7");

        tfStad.setText("jTextField8");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBranch)
                        .addGap(82, 82, 82)
                        .addComponent(tfBranch))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAdress)
                        .addGap(81, 81, 81)
                        .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPartnerId)
                        .addGap(63, 63, 63)
                        .addComponent(tfPartnerId, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStad)
                        .addGap(93, 93, 93)
                        .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNamn)
                        .addGap(85, 85, 85)
                        .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKontaktperson)
                        .addGap(40, 40, 40)
                        .addComponent(tfKontaktperson, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKontaktEpost)
                        .addGap(42, 42, 42)
                        .addComponent(tfKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefon)
                        .addGap(79, 79, 79)
                        .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpara)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartnerId)
                    .addComponent(tfPartnerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontaktperson)
                    .addComponent(tfKontaktperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontaktEpost)
                    .addComponent(tfKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranch)
                    .addComponent(tfBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStad)
                    .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpara))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:
        
        String partnerId = tfPartnerId.getText();
        String namn = tfNamn.getText();
        String kontaktperson = tfKontaktperson.getText();
        String kontaktepost = tfKontaktEpost.getText();
        String telefon = tfTelefon.getText();
        String adress = tfAdress.getText();
        String branch = tfBranch.getText();
        String stad = tfStad.getText();
        
        if(!Validering.isOnlyLetters(namn) && !Validering.isValidEpost(kontaktepost) && !Validering.isOnlyLetters(stad) 
                && !Validering.isOnlyLetters(kontaktperson))
        {
            return;
        }
        
        try
        {
            String sql = "UPDATE partner SET partnerId = '" + partnerId + "', namn = '" + namn + "', kontaktperson = '" + 
                    kontaktepost + "', telefon = '" + telefon + "', adress = '" + adress + "', branch = '" + branch + 
                    "', stad = '" + stad + "' WHERE pid = " + partnerUppgifter;
            idb.update(sql);
            JOptionPane.showMessageDialog(null, "Uppgifterna har uppdaterats!");
        }
        
        catch (InfException ex)
        {
            JOptionPane.showMessageDialog(null, "Något gick fel: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnSparaActionPerformed

    public void hamtaPartnerId()
    {
        String sqlFraga = "SELECT pid FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String partnerId = idb.fetchSingle(sqlFraga);
            tfPartnerId.setText(partnerId);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaNamn()
    {
        String sqlFraga = "SELECT namn FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String namn = idb.fetchSingle(sqlFraga);
            tfNamn.setText(namn);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaKontaktperson()
    {
        String sqlFraga = "SELECT kontaktperson FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String kontaktperson = idb.fetchSingle(sqlFraga);
            tfKontaktperson.setText(kontaktperson);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaKontaktEpost()
    {
        String sqlFraga = "SELECT kontaktepost FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String kontaktepost = idb.fetchSingle(sqlFraga);
            tfKontaktEpost.setText(kontaktepost);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaTelefon()
    {
        String sqlFraga = "SELECT telefon FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String telefon = idb.fetchSingle(sqlFraga);
            tfTelefon.setText(telefon);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAdress()
    {
        String sqlFraga = "SELECT adress FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String adress = idb.fetchSingle(sqlFraga);
            tfAdress.setText(adress);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaBranch()
    {
        String sqlFraga = "SELECT branch FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String branch = idb.fetchSingle(sqlFraga);
            tfBranch.setText(branch);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaStad()
    {
        String sqlFraga = "SELECT stad FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String stad = idb.fetchSingle(sqlFraga);
            tfStad.setText(stad);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartnerUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartnerUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartnerUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartnerUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // PartnerUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblKontaktEpost;
    private javax.swing.JLabel lblKontaktperson;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPartnerId;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfBranch;
    private javax.swing.JTextField tfKontaktEpost;
    private javax.swing.JTextField tfKontaktperson;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfPartnerId;
    private javax.swing.JTextField tfStad;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
