/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author jakobolofsson
 */
public class ProjektDetaljer extends javax.swing.JFrame {
    private InfDB idb;
    private String aktuelltProjekt;
    /**
     * Creates new form ProjektDetaljer
     */
    public ProjektDetaljer(InfDB idb, String aktuelltProjekt) {
        this.idb = idb;
        this.aktuelltProjekt = aktuelltProjekt;
        initComponents();
        hamtaLabelNamn();
        hamtaProjektNamn();
        hamtaPid();
        hamtaBeskrivning();
        hamtaStartdatum();
        hamtaSlutdatum();
        hamtaKostnad();
        hamtaStatus();
        hamtaPrioritet();
        hamtaProjektchef();
        hamtaLand();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfPid = new javax.swing.JTextField();
        tfProjektnamn = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        tfStartdatum = new javax.swing.JTextField();
        tfSlutdatum = new javax.swing.JTextField();
        tfKostnad = new javax.swing.JTextField();
        lblAktuelltProjektNamn = new javax.swing.JLabel();
        tfStatus = new javax.swing.JTextField();
        tfPrioritet = new javax.swing.JTextField();
        tfProjektchef = new javax.swing.JTextField();
        tfLand = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblPid = new javax.swing.JLabel();
        lblProjektnamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblStartdatum = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        lblKostnad = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPrioritet = new javax.swing.JLabel();
        lblProjektChef = new javax.swing.JLabel();
        lblLand = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfPid.setText("jTextField1");

        tfProjektnamn.setText("jTextField2");
        tfProjektnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProjektnamnActionPerformed(evt);
            }
        });

        tfBeskrivning.setText("jTextField3");

        tfStartdatum.setText("jTextField4");

        tfSlutdatum.setText("jTextField5");

        tfKostnad.setText("jTextField6");

        lblAktuelltProjektNamn.setText("jLabel1");

        tfStatus.setText("jTextField7");

        tfPrioritet.setText("jTextField8");

        tfProjektchef.setText("jTextField9");

        tfLand.setText("jTextField10");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPid.setText("Projekt-ID:");

        lblProjektnamn.setText("Namn:");

        lblBeskrivning.setText("Beskrivning:");

        lblStartdatum.setText("Startdatum:");

        lblSlutdatum.setText("Slutdatum:");

        lblKostnad.setText("Kostnad:");

        lblStatus.setText("Status:");

        lblPrioritet.setText("Prioritet:");

        lblProjektChef.setText("Projektchef:");

        lblLand.setText("Land:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAktuelltProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblProjektnamn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBeskrivning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblStartdatum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSlutdatum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKostnad)
                            .addComponent(lblStatus)
                            .addComponent(lblPrioritet)
                            .addComponent(lblProjektChef)
                            .addComponent(lblLand))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfProjektchef)
                            .addComponent(tfPrioritet)
                            .addComponent(tfStatus)
                            .addComponent(tfKostnad)
                            .addComponent(tfLand, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAktuelltProjektNamn)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPid)
                    .addComponent(lblKostnad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProjektnamn)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeskrivning)
                    .addComponent(lblPrioritet))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartdatum)
                    .addComponent(lblProjektChef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSlutdatum)
                    .addComponent(lblLand))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProjektnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProjektnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProjektnamnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void hamtaLabelNamn(){
        String sqlFraga = "SELECT projektnamn FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        lblAktuelltProjektNamn.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
        
    public void hamtaProjektNamn(){
        String sqlFraga = "SELECT projektnamn FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfProjektnamn.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
    
    public void hamtaPid(){
        String sqlFraga = "SELECT pid FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfPid.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
    
     public void hamtaBeskrivning(){
        String sqlFraga = "SELECT beskrivning FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfBeskrivning.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
     
     public void hamtaStartdatum(){
        String sqlFraga = "SELECT startdatum FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfStartdatum.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
    
    public void hamtaSlutdatum(){
        String sqlFraga = "SELECT slutdatum FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfSlutdatum.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
    
    public void hamtaKostnad(){
        String sqlFraga = "SELECT kostnad FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfKostnad.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
    
    public void hamtaStatus(){
        String sqlFraga = "SELECT status FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfStatus.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
     
    public void hamtaPrioritet(){
        String sqlFraga = "SELECT prioritet FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfPrioritet.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
    
    public void hamtaProjektchef(){
        String sqlFraga = "SELECT projektchef FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfProjektchef.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
    
    public void hamtaLand(){
        String sqlFraga = "SELECT land FROM projekt WHERE pid = "+aktuelltProjekt;
        try{
        String projektNamn = idb.fetchSingle(sqlFraga);
        tfLand.setText(projektNamn);
        }
        catch(InfException ex){
        System.out.println(ex.getMessage());
    } }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektDetaljer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektDetaljer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektDetaljer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektDetaljer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new ProjektDetaljer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAktuelltProjektNamn;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblPrioritet;
    private javax.swing.JLabel lblProjektChef;
    private javax.swing.JLabel lblProjektnamn;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfKostnad;
    private javax.swing.JTextField tfLand;
    private javax.swing.JTextField tfPid;
    private javax.swing.JTextField tfPrioritet;
    private javax.swing.JTextField tfProjektchef;
    private javax.swing.JTextField tfProjektnamn;
    private javax.swing.JTextField tfSlutdatum;
    private javax.swing.JTextField tfStartdatum;
    private javax.swing.JTextField tfStatus;
    // End of variables declaration//GEN-END:variables
}
