/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author elisl
 */
public class VisaPartnerUppgifter extends javax.swing.JFrame {
    InfDB idb;
    String partnerUppgifter;
    /**
     * Creates new form VisaPartnerUppgifter
     */
    public VisaPartnerUppgifter(InfDB idb,String partnerUppgifter) {
        this.idb = idb;
        this.partnerUppgifter = partnerUppgifter;
        initComponents();
        hamtaPartnerId();
        hamtaNamn();
        hamtaKontaktperson();
        hamtaKontaktEpost();
        hamtaTelefon();
        hamtaAdress();
        hamtaBranch();
        hamtaStad();
    }
 public void hamtaPartnerId()
    {
        String sqlFraga = "SELECT pid FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String partnerId = idb.fetchSingle(sqlFraga);
            lblPartnerID.setText("PartnerID: "+partnerId);
            
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaNamn()
    {
        String sqlFraga = "SELECT namn FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String namn = idb.fetchSingle(sqlFraga);
            lblNamn.setText("Namn: "+namn);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaKontaktperson()
    {
        String sqlFraga = "SELECT kontaktperson FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String kontaktperson = idb.fetchSingle(sqlFraga);
            lblKontaktperson.setText("Kontaktperson: "+kontaktperson);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaKontaktEpost()
    {
        String sqlFraga = "SELECT kontaktepost FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String kontaktepost = idb.fetchSingle(sqlFraga);
            lblKontaktEpost.setText("Kontakt-epost: "+kontaktepost);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaTelefon()
    {
        String sqlFraga = "SELECT telefon FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String telefon = idb.fetchSingle(sqlFraga);
            lblTelefon.setText("Telefon: "+telefon);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaAdress()
    {
        String sqlFraga = "SELECT adress FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String adress = idb.fetchSingle(sqlFraga);
            lblAdress.setText("Adress: "+adress);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaBranch()
    {
        String sqlFraga = "SELECT branch FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String branch = idb.fetchSingle(sqlFraga);
            lblBranch.setText("Bransch: "+branch);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    
    public void hamtaStad()
    {
        String sqlFraga = "SELECT stad FROM partner WHERE pid = "+partnerUppgifter;
        try
        {
            String stad = idb.fetchSingle(sqlFraga);
            lblStad.setText("Stad: "+stad);
        }
        catch(InfException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPartnerID = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblKontaktperson = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblKontaktEpost = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPartnerID.setText("PartnerID");

        lblBranch.setText("Branch");

        lblNamn.setText("Namn");

        lblKontaktperson.setText("Kontaktperson");

        lblTelefon.setText("Telefon");

        lblKontaktEpost.setText("Kontakt-epost");

        lblAdress.setText("Adress");

        lblStad.setText("Stad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPartnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKontaktperson, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                        .addComponent(lblKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblPartnerID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKontaktperson)
                .addGap(12, 12, 12)
                .addComponent(lblKontaktEpost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdress)
                .addGap(8, 8, 8)
                .addComponent(lblBranch)
                .addGap(18, 18, 18)
                .addComponent(lblStad)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaPartnerUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaPartnerUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaPartnerUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaPartnerUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VisaPartnerUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblKontaktEpost;
    private javax.swing.JLabel lblKontaktperson;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPartnerID;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTelefon;
    // End of variables declaration//GEN-END:variables
}
